Hometask5
Levliv/HomeWorks pull request #16
Opened 2021-11-20 22:33 UTC by Levliv

God, help this code to work, Amen.

2021-12-01 20:49 UTC, yurii-litvinov requested changes

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/AttributeClasses/MyTestAttribute.cs
> +        public string Ignore = null;
Паблик-поля автоматически влекут незачёт за задачу, используйте свойства

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/AttributeClasses/MyTestAttribute.cs
> +        public object Expected = null;
Думаю, что оно не object, а Type

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/MyNUnit.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Пора переходить на .NET 6

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/Testdata/Test1/Test1/Test1.sln
> +﻿
Хм, тестам точно нужна отдельная .sln-ка?

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/Program.cs
> +            }
Лучше тут return, чтобы дальше было без else и лишнего отступа

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        /// Concurent collection to strore data about the tests
store

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        public static BlockingCollection<TestStrcuct> MyTests { get; private set; }
Пргрмирвоне не дл Вса :)

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                    $"{((testResult.IsIgnored)? "Ignored, message = " + testResult.Ignore_message:"")}");
```suggestion
                    $"{((testResult.IsIgnored) ? "Ignored, message = " + testResult.Ignore_message : "")}");
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                    $"{(testResult.IsFailed ? $"Failed + Expected: {testResult.Expected}, Got: {testResult.Got}":"")}" +
```suggestion
                    $"{(testResult.IsFailed ? $"Failed + Expected: {testResult.Expected}, Got: {testResult.Got}" : "")}" +
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        public static BlockingCollection<TestStrcuct> MyTests { get; private set; }
Статическое мутабельное поле (даже если оно свойство) --- это глобальная переменная. Глобальная переменная --- это ересь.

<img width="200" src="https://user-images.githubusercontent.com/706768/144308298-90dc0d73-b856-4268-bd06-c738a647e74a.png">

Тут стоило всё-таки сделать TestRunner нестатическим классом, раз уж ему таки надо хранить состояние. Либо возвращать коллекцию TestStrcuct-ов из Start и принимать в PrintTestResults

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +            var downloadeddlls = new HashSet<string>();
ddllssddsllsesd? :) camelCase же. Так это выглядит вообще будто кошка по клавиатуре прошла

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        /// Loadign the dll and starting the tests, Cheks for not repeated dlls
:(

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        /// <param name="path">Path to folder, loading all the dlls in all the directorieds beneath it as well</param>
```suggestion
        /// <param name="path">Path to folder, loading all the dlls in all the directories beneath it as well</param>
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +            foreach(var dll in dllFilesNotRepeated)
```suggestion
            foreach (var dll in dllFilesNotRepeated)
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                var assembly = Assembly.LoadFrom(dll);
Грузить их в принципе тоже можно было параллельно

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                Parallel.ForEach(types, TestStarter);
А так получится, что пока одна сборка не оттестировалась, остальные ждут. И если у Вас сотня сборок по одному классу, то параллельности не получится.

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        /// Invokes the methods with attribues, calling methods corresponding to the attribute type
```suggestion
        /// Invokes the methods with attributes, calling methods corresponding to the attribute type
```
Вообще, столько опечаток --- это прямо очень плохо. Опечататься в комментарии не страшно, а вот не там поставить запятую в коде отделения ступени ракеты --- и ракета за миллионы долларов падает на ближайший город.

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                test = x => MethodsWithBeforeAndAfterClassAttribute(x, obj);
```suggestion
            {
                test = x => MethodsWithBeforeAndAfterClassAttribute(x, obj);
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +            if (typeof(AttributeType) == typeof(BeforeAttribute) || typeof(AttributeType) == typeof(AfterAttribute)){
```suggestion
            if (typeof(AttributeType) == typeof(BeforeAttribute) || typeof(AttributeType) == typeof(AfterAttribute))
            {
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                throw new Exception("Wrong attribute type");
Никогда не кидайте просто Exception, кроме как для отладки. Оно слишком общее, его нельзя поймать и обработать

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        public static object ConstuctorFinder(MethodInfo methodInfo)
Он не ищет конструктор, он создаёт объект. Кстати, класс Activator делает как раз это, может, стоит его использовать

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +            MyTestAttribute attribute = (MyTestAttribute)methodInfo.GetCustomAttribute(typeof(MyTestAttribute), true);
```suggestion
            var attribute = (MyTestAttribute)methodInfo.GetCustomAttribute(typeof(MyTestAttribute), true);
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                        object result = methodInfo.Invoke(obj, null);
Нет принципиальной разницы, attribute.Expected == null или нет. Запускали бы всегда в try/catch, и потом бы смотрели, что получилось. А то копипаст

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                        MethodsInvoker<BeforeAttribute>(methodInfo.DeclaringType);
Не-а, тут надо принимать уже инстанс. Потому что этот метод обычно выставляет состояние у тестового объекта. Плохо, если мы проинициализировали один объект, а запустили тест в другом.

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                            MyTests.Add(new TestStrcuct(methodInfo, isPassed: true, expected: attribute.Expected, timeConsumed: watch.ElapsedMilliseconds)); ;
Стоп, если тестовый метод вернул объект-исключение, а не бросил его, это нормально?

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                            MyTests.Add(new TestStrcuct(methodInfo, isPassed: true, expected: attribute.Expected, timeConsumed: watch.ElapsedMilliseconds)); ;
```suggestion
                            MyTests.Add(new TestStrcuct(methodInfo, isPassed: true, expected: attribute.Expected, timeConsumed: watch.ElapsedMilliseconds));
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +        }
```suggestion
            object result = methodInfo.Invoke(obj, null);
        }
```
Но зачем нам вообще result?

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +            if (!methodInfo.IsStatic && ((methodInfo.GetCustomAttribute(typeof(BeforeClassAttribute)) != null) || (methodInfo.GetCustomAttribute(typeof(AfterClassAttribute)) != null)))
Очень длинная строчка, перенесите

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                Console.WriteLine("Wrong ch");
Нет :)

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestRunner.cs
> +                Console.WriteLine("Theare");
Неееет

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +    /// Template for data restored after test invokation
```suggestion
    /// Template for data restored after test invoсation
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +        public string Ignore_message { get; }
CamelCase please :)

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +        /// Containg the actual(returned from the method) value got by test invocation
:(

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +        /// Containig message is case test in suppposed to be ignored
:(

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +        /// Constructor to restore the information about tests
store?

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnit/TestStrcuct.cs
> +            bool isIgnored = false, long timeConsumed = 0, string errorMessage = null, object expected = null, object got = null,  string ignore_message = null)
camelCase

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/MyNUnitTests/MyNUnitTests.cs
> +        /// Chechking that when only method have attributes everything works fine
```suggestion
        /// Checking that when only method have attributes everything works fine
```

2021-12-01 20:49 UTC, yurii-litvinov commented on HomeTask5/Testdata/Test1/Test1/Test1.cs
> +    }
Это, конечно, тестовые тесты, но стайлгайд и тут надо навести

2021-12-05 09:58 UTC, Levliv commented on HomeTask5/MyNUnit/AttributeClasses/MyTestAttribute.cs
> +        public object Expected = null;
Я хотел хотел хранить в этой переменной не только информацию о исключении, но еще, допустим, значение, которое должно быть результатом метода.
Разве с Type это не будет сложнее?
@yurii-litvinov

2022-03-07 15:15 UTC, yurii-litvinov requested changes

2022-04-10 20:19 UTC, Levliv commented on MyNUnit/MyNUnit/TestRunner.cs
> +        var downloadedDlls = new HashSet<string>();
Хотел обозначить как "загруженные"

2022-04-14 13:02 UTC, yurii-litvinov requested changes

2022-04-14 16:58 UTC, yurii-litvinov approved these changes
Окей, зачтена

2022-04-14 16:58 UTC, yurii-litvinov commented on MyNUnit/MyNUnit/TestRunner.cs
> +        ArgumentNullException.ThrowIfNull(attribute);
Строго говоря, attribute --- это не аргумент, поэтому ArgumentNullException тут неуместно

2022-04-15 10:20 UTC, merged