My lazy
Levliv/HomeWorks pull request #20
Opened 2021-11-25 19:38 UTC by Levliv

2021-12-01 15:58 UTC, yurii-litvinov requested changes

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
.gitignore надо в корень репозитория, тут нет причин игнорить что-то своё в каждой папке

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazy/ILazy.cs
> +    public interface ILazy<T>
```suggestion
    public interface ILazy<out T>
```
Вот хорошее объяснение вариантности: http://tomasp.net/blog/variance-explained.aspx/

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazy/MultiThreadLazy.cs
> +        public volatile bool IsRecorded = false;
public-полей быть не должно, тем более мутабельных. Это же нарушение и инвариантов класса, и инкапсуляции, и всего

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazy/MultiThreadLazy.cs
> +        /// Storing a Recocdet afer Lazy init result
Что? :)

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazy/OneThreadLazy.cs
> +        /// <summary>
```suggestion
        private Func<T> _supplier;
        
        /// <summary>
```

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazy/MultiThreadLazy.cs
> +        public T RecordedResult { get; private set; }
А зачем это public? Есть же Get()

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/MultiThreadLazyTest.cs
> +        /// <summary>
```suggestion
        }

        /// <summary>
```

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/OneThreadLazyTests.cs
> +        public void TestForCorrectenss(object d)
```suggestion
        /// Tesing The correctness on Lazy Computation
        /// </summary>
        [TestCaseSource(nameof(TestData))]
        public void TestForCorrectness(object d)
```

2021-12-01 15:58 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/OneThreadLazyTests.cs
> +        }
А для многопоточной Lazy таких вещей не проверяется?

2021-12-07 12:12 UTC, yurii-litvinov requested changes
Надо немного доисправлять

2021-12-07 12:12 UTC, yurii-litvinov commented on MyLazy/MyLazy/MultiThreadLazy.cs
> +        private volatile bool IsRecorded = false;
А поля именуются со строчной всегда.

2021-12-07 12:12 UTC, yurii-litvinov commented on MyLazy/MyLazy/OneThreadLazy.cs
> +        /// <summary>
Не поправлено, надо пустую строчку перед комментариями

2021-12-07 12:12 UTC, yurii-litvinov commented on MyLazy/MyLazy/OneThreadLazy.cs
> +        private bool IsRecorded = false;
И тут тоже надо именование поправить

2021-12-07 12:12 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/OneThreadLazyTests.cs
> +        }
Хорошо, теперь у нас появился некий копипаст в тестах, который можно победить с помощью TestCaseSource, который бы возвращал разные сорта Lazy (точнее, способы их создать, можно прямо методы фабрики). Тогда можно было бы написать один тестовый класс, тестирующий по абсолютно одинаковым сценариям обе реализации Lazy.

2021-12-07 18:38 UTC, Levliv commented on MyLazy/MyLazyTests/OneThreadLazyTests.cs
> +        }
Теперь у нас есть статическое мутабельное поле, значит ересь?
@yurii-litvinov

2021-12-18 20:55 UTC, yurii-litvinov approved these changes
Good enough, зачтена

2021-12-18 20:55 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/BasicTests.cs
> +        public static IEnumerable TestData = new object[] { 12, "abc", 'c' };
Зачем оно public-поле? :)

2021-12-18 20:55 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/BasicTests.cs
> +    public class OneThreadLazyTests
Это уже неправдивое название

2021-12-18 20:55 UTC, yurii-litvinov commented on MyLazy/MyLazyTests/MultiThreadLazyTest.cs
> +        }
Это должно быть верно и для обычного Lazy

2021-12-20 13:50 UTC, merged