My ftp
Levliv/HomeWorks pull request #22
Opened 2021-11-27 16:14 UTC by Levliv

2021-12-01 17:59 UTC, yurii-litvinov requested changes
Новый пуллреквест вроде незачем, можно было в старом поправить

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
.gitignore лучше в корне репозитория. Вряд ли есть нужда игнорить что-то конкретно в этой папке

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/.editorconfig
> +dotnet_diagnostic.CS8604.severity = none
Не уверен, что стоит во всём проекте nullability-предупреждения выключать. Тогда уж можно было отключить nullability-анализ вовсе в проектном файле. А то сейчас он как бы есть, а ругаться ему запрещено :)

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Program.cs
> +        if (IPAddress.TryParse(args[0], out ip) && int.TryParse(args[1], out port))
```suggestion
        if (IPAddress.TryParse(args[0], out IPAddress? ip) && int.TryParse(args[1], out int port))
```

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Program.cs
> +        }
А если нет, то надо справку по использованию напечатать

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Program.cs
> +            var task1 = Task.Run(() => server.ServerMethodAsync().Wait());
Что-то тут злое написано. Дёргается асинхронный метод, но ему делается Wait, но он обёрнут в Task.Run, который никто не await-ит. Что? :) `await server.ServerMethodAsync();` просто. Это то же самое, но требует `static async Task Main`

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +public class Server
```suggestion
namespace MyFTP;

public class Server
```

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +    public Server(IPAddress ip, int port, string param = "../../../.")
param надо назвать как-то более по-человечески

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +        var dir = Path.GetFullPath(DataPath + ".");
Интересно, у Вас DataPath по умолчанию принимает "../../../.", и тут ещё дописывается точка, и получается что?

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +            await Task.Run(async () =>
await и Task.Run на асинхронный метод --- это более-менее взаимнообратные операции. Task.Run запустит задачу на тредпуле, но await остановит текущий поток (точнее, вернёт управление в цикл обработки событий, если он есть). Так что нет, двух клиентов сразу так обслужить не получится. Надо не await-ить прямо сейчас, а сложить в список и заawait-ить всё сразу, в конце

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +            using var socket = await listener.AcceptSocketAsync();
Без await ниже сокет сдохнет до того, как из него начнут читать, так что using должен быть не здесь, а ниже

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +/// Class for Client of tcp protocol
Он TCP, не tcp :)

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +
Комментарии от комментируемой сущности пустой строкой не отделяются

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public GetResponseStruct GetResponse { get; private set; }
Сделайте ещё паблик-свойство, которое пароль от Вашего онлайн-банка возвращает :) Зачем это всё вызывающему знать-то?

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        TcpClient = new TcpClient(ipString, port);
Этот конструктор тут же пытается подключиться, что заблокирует вызывающего (может, надолго --- пока не пройдёт таймаут, а у TCP он может быть довольно долгим). Тут надо ConnectAsync вызывать, и даже не тут, а уже когда пытаемся что-то сделать на сервере.

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public void ClientRequest(string requestString)
Не, этим пусть занимается CLI. Сам клиент должен предоставлять методы Get и List, парсинг пользовательского ввода --- не его дело

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        var splitedRequestString = requestString.Split(" ");
split**t**edRequestString

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        if (request == "1")
```suggestion
        else if (request == "1")
```

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public RequestType FtpRequestType { get; private set; }
Это правда часть состояния класса, а не параметр запроса? Тут и ниже, подумайте, что можно не хранить.

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public void PrintResults()
Это тоже не проблема клиента. Ввод-вывод оставьте Main

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        for (var i = 1; i < int.Parse(strings[0]) * 2; i+=2)
```suggestion
        for (var i = 1; i < int.Parse(strings[0]) * 2; i += 2)
```

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        var messageLenght = int.Parse(streamReader.ReadLine());
messageLeng**th**. И GitHub Actions недоволен nullability (отсутствием проверки результата ReadLine на null)

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/GetResponseStruct.cs
> +        /// Data in bytes recived got by tcp
recived got?

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Program.cs
> +        string? request;
Не объявляйте переменные раньше времени и без значения

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Program.cs
> +                request = Console.ReadLine();
Не, не надо. Надо всё из аргументов, чтобы можно было делать что-то вроде `dotnet run -- 127.0.0.1 8888 --list .`

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Program.cs
> +                if(request == null || ip == null)
```suggestion
                if (request == null || ip == null)
```

2021-12-01 17:59 UTC, yurii-litvinov commented on MyFTP/MyFTPTests/MyFTPClientTests.cs
> +        var task1 = Task.Run(() => server.ServerMethodAsync().Wait());
:(

2021-12-04 11:41 UTC, Levliv commented on MyFTP/MyFTPClient/Client.cs
> +    public GetResponseStruct GetResponse { get; private set; }
Это чтобы тесты прошли, они же модульные, им хотелось бы получить данные вот именно из этого свойства до обработки этих данных другими методами

2021-12-04 11:47 UTC, Levliv commented on MyFTP/MyFTPClient/Client.cs
> +    public void PrintResults()
Если мы вынесем это в Main, то свойства, которые Вы просили сделать private несколько строк выше точно придется делать public, или имелось ввиду что-то другое?
@yurii-litvinov

2021-12-04 11:55 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public GetResponseStruct GetResponse { get; private set; }
В боевом коде не должно быть ничего для тестов, тем более чего-то, что сильно портит архитектуру. Модульные тесты должны тестировать только видимое извне поведение. Если хочется тестировать что-то внутри, разбейте класс на более мелкие модули тогда.

2021-12-04 11:58 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public void PrintResults()
Совершенно незачем. Делаете клиенту метод List, который возвращает IEnumerable<ResponseFormat>, да и всё. Я бы даже сказал, что ResponseFormat не нужен, Можно List<(string, bool)> возвращать, но дело вкуса.

2021-12-04 19:32 UTC, Levliv commented on MyFTP/MyFTPClient/Client.cs
> +    public void PrintResults()
Хорошо, спасибо

2021-12-04 21:19 UTC, Levliv commented on MyFTP/MyFTP/MyFTP/Server.cs
> +        var dir = Path.GetFullPath(DataPath + ".");
DataPath еще дальше используется, и он нужен без точки, ну выглядит так себе, конечно

2021-12-20 16:07 UTC, yurii-litvinov requested changes

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/MyFTPServer.csproj
> +    <Nullable>disable</Nullable>
Лучше enable, а то ниже CI ругается

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Program.cs
> +            Console.WriteLine("Program requires two command line options, use them in the following order: ip, port");
Не-а, оно так упадёт при попытке получить args[0]. Надо сначала проверить количество аргументов

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +        }
```suggestion
        return (-1, new byte[0]);
```

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +        List<Task> list = new List<Task>();
```suggestion
        var list = new List<Task>();
```

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +            await Task.WhenAll(list);
Не-а. Так у Вас запускается в отдельном потоке слушалка порта, но основной поток тут же останавливается на await-е. Второй клиент не сможет подключиться, потому что его  тут не ждёт никто. Надо listener.AcceptSocketAsync делать в основном потоке, а await Task.WhenAll(list); делать вне while

2021-12-20 16:07 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    private NetworkStream? MyStreamReader;
Ему вообще нет никакой причины быть полем

2021-12-27 10:20 UTC, yurii-litvinov requested changes
Мне кажется, стало хуже :)

2021-12-27 10:20 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +                            streamWriter.WriteLine(List(DataPath + requestPath).Result);
Если Вы используете Result для асинхронной задачи, это уже говорит о том, что Вы делаете что-то не так. Тут await, конечно

2021-12-27 10:20 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTP/Server.cs
> +                            streamWriter.WriteLine(sizeOfMessage);
Есть всякие асинхронные варианты методов, в Вашем асинхронном коде стоило бы использовать именно их. А то мало профита в async, если внутри все вызовы блокирующие — забьёте все потоки из пула просто

2021-12-27 10:20 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +        });
await Task.Run не очень полезно. Тут тоже надо асинхронные версии библиотечных методов использовать

2021-12-27 10:20 UTC, yurii-litvinov commented on MyFTP/MyFTPClient/Client.cs
> +    public async Task<List<ResponseFormat>> List(string path)
А ещё стоит CancellationToken принимать и передавать его во все асинхронные библиотечные штуки. Длительные запросы должны быть отменяемы просто по правилам хорошей архитектуры.

2022-01-26 12:09 UTC, yurii-litvinov requested changes
Я бы очень рекомендовал прочитать главу про async-и в CLR via C# Джеффри Рихтера (только не ниже 4-го издания). Ну и вообще книжку очень рекомендую. А то сейчас видно, что Вы не имеете идей, что за async-и :)

2022-03-07 12:56 UTC, yurii-litvinov requested changes

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +public class ClientEngine
```suggestion
namespace MyFTP;

public class ClientEngine
```

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +    /// Tcp Client string inforation about current connection.
```suggestion
    /// Tcp Client string information about current connection.
```
И почему string?

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +    /// List request method, getting information about the files and dirictories found by the provided path.
```suggestion
    /// List request method, getting information about the files and directories found by the provided path.
```

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +            await tcpClient.ConnectAsync(IpString, Port);
Поскольку это потенциально длительная операция, в ListAsync и конкретно сюда надо передавать CancellationToken, чтобы извне можно было её отменить.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +        await streamWriter.WriteLineAsync(1 + " " + path);
```suggestion
        await streamWriter.WriteLineAsync($"1 {path}");
```

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +    /// Getting the file data, stroing in the current file, by provided path.
stroing? Я даже не понял, что имеется в виду. storing? Но тогда это грамматически не очень.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +            await tcpClient.ConnectAsync(IpString, Port);
Тут тоже надо CancellationToken

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +        var bytes = streamBinaryReader.ReadBytes(messageLength);
Надо придумать способ не зачитывать весь файл в память (потому что файлы могут быть большие и в память могут не поместиться). Посмотрите CopyToAsync.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/GetResponseStruct.cs
> +﻿namespace MyFTP
file-scoped namespaces?

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/GetResponseStruct.cs
> +﻿namespace MyFTP
И надо предупреждение про заголовок файла заглушить. CI должен проходить без предупреждений.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +    public static async Task Main(string[] args)
Это можно было без класса и Main всякого написать, top-level statements есть. Main нынче вообще не нужны.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +            string? path = args[2];
args[2] --- это path или requestCode?

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +                    Console.WriteLine(Encoding.UTF8.GetString(getResponse.Data));
Не, надо файл на клиенте создавать, иначе толку ноль от такой программы

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +                    Console.WriteLine(item.Name + " " + item.IsDir + " ");
Используйте string interpolation

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/Program.cs
> +            var command = string.Empty;
И управление у Вас правда сюда попадает? У меня нет.

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +            await streamWriter.WriteLineAsync($"{-1} ");
```suggestion
            await streamWriter.WriteLineAsync("-1 ");
```

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +    public async Task GetServerAsync(StreamWriter streamWriter, string path)
Мне кажется, этот  метод и некоторые методы ниже не должны быть public

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +        return;
:thinking:

2022-03-07 12:56 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPTests/ClientTests.cs
> +}
Стоило ещё проверить с двумя клиентами одновременно

2022-03-19 17:15 UTC, Levliv commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +        return;
Управление не может "проваливаться" из одной метки case ('label') в другую

Если [оператор switch](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/statements/selection-statements#the-switch-statement) содержит более одного раздела переключения, необходимо явно завершить все разделы, включая последний, используя одно из следующих ключевых слов:

[return](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/statements/jump-statements#the-return-statement)
[goto](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/statements/jump-statements#the-goto-statement)
[break](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/statements/jump-statements#the-break-statement)
[throw](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/throw)
Если необходимо реализовать поведение "проваливания" из одного раздела в следующий, используйте выражение goto case #.

2022-04-06 14:12 UTC, yurii-litvinov requested changes
Уже совсем почти ок, надо только код привести в порядок

2022-04-06 14:12 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +        var strings = message.Split();
Тоже надо победить все предупреждения (тем более что тут даже по делу)

2022-04-06 14:12 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +﻿// <copyright file="Program.cs" company="PlaceholderCompany">
:(

2022-04-06 14:12 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +    private static async Task Main(string[] args)
Это лишние церемонии, в C# 10 есть top-level statements

2022-04-06 14:12 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPClient/Program.cs
> +                throw new ArgumentNullException("Ip should be not NULL");
ThrowIfNull лучше

2022-04-06 14:12 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/Program.cs
> +    public static async Task Main(string[] args)
Тут тоже, кстати

2022-04-10 15:25 UTC, Levliv commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +public class ClientEngine
fixed

2022-04-10 15:38 UTC, Levliv commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +        var strings = message.Split();
fixed

2022-04-10 15:59 UTC, Levliv commented on MyFTP/MyFTP/MyFTPClient/ClientEngine.cs
> +        IpString = ipString;
fixed

2022-04-14 13:35 UTC, yurii-litvinov approved these changes
В целом ок, а Вы и так страдали с этой задачей достаточно. Зачтена.

2022-04-14 13:35 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +    private IPAddress Ip { get; set; }
private- автоматические свойства не нужны, они могут быть просто полями

2022-04-14 13:35 UTC, yurii-litvinov commented on MyFTP/MyFTP/MyFTPServer/ServerEngine.cs
> +    /// Gets stops the server, all requests received before cancellation will be processed.
Gets stops the server, что? :) Это ведь не метод. Gets cancellation token that can be used to stop the server?

2022-04-14 14:53 UTC, merged