Develop hometask2
Levliv/HomeWorks pull request #5
Opened 2021-09-28 21:45 UTC by Levliv

2021-09-30 11:23 UTC, yurii-litvinov requested changes

2021-09-30 11:23 UTC, yurii-litvinov commented on HomeTask2/InterTask/LazyFactory.cs
> +        public OneThereadLazyFactory(Func<T> supplier)
OneThereadLazyFactory, што? :) И это ж не фабрика, это сам Lazy

2021-09-30 11:23 UTC, yurii-litvinov commented on HomeTask2/InterTask/LazyFactory.cs
> +        public T _recordedResult { get; set; }
И главное, что опять-таки, свойство тут не нужно.

2021-09-30 11:23 UTC, yurii-litvinov commented on HomeTask2/InterTask/LazyFactory.cs
> +                lock (balanceLock)
Вот между предыдущей и этой строчкой ещё несколько потоков могли успеть полностью исполнить метод Get, так что supplier вызовется не по делу. Надо после взятия замка ещё раз проверить, не посчитал ли кто уже.

2021-09-30 11:23 UTC, yurii-litvinov commented on HomeTask2/InterTask/LazyFactory.cs
> +                    _isRecorded = true;
Помните, что процессор может переставлять инструкции, и есть кеш, так что соседние потоки могут увидеть сначала результат 99-й строки, и затем только 98-й (и вернуть null, тем самым покрешив всю программу)

2021-09-30 11:23 UTC, yurii-litvinov commented on HomeTask2/InterTask/Program.cs
> +        }
Ммммкей, но думаю, что удалить это было бы нелишне

2021-10-08 20:22 UTC, Levliv commented on HomeTask2/InterTask/LazyFactory.cs
> +namespace InterTask
Фантазия слишком быстро закончилась, поэтому Inter)) Это Вы еще названия веток не видели :)

2021-10-14 13:46 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/MultiThreadLazy.cs
> +        [TestCase(20, ExpectedResult=20)]
```suggestion
        [TestCase(10, ExpectedResult = 10)]
        [TestCase(20, ExpectedResult = 20)]
```

2021-10-14 13:48 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/OneThreadLazy.cs
> +        }
Это не то, что я хотел в плане борьбы с копипастом в тестах. Хочется, чтобы два варианта реализации ILazy тестировались на одном и том же наборе тестов, кроме теста на гонки, который применим только к многопоточному варианту.

2021-10-14 13:48 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/OneThreadLazy.cs
> +    }
А ещё совсем нет теста на то, что однопоточная Lazy вызывает функцию единожды.

2021-10-14 13:49 UTC, yurii-litvinov commented on HomeTask2/LazyFactory/ILazy.cs
> +    /// Interface ILazy
Это и так понятно, но **что** это за интерфейс?

2021-10-14 13:50 UTC, yurii-litvinov commented on HomeTask2/LazyFactory/MultiThreadLazy.cs
> +            }
```suggestion
            _supplier = supplier ?? throw new ArgumentNullException("null ptr is not allowed");
```

2021-10-14 13:51 UTC, yurii-litvinov commented on HomeTask2/LazyFactory/OneThreadLazy.cs
> +        private volatile bool _isRecorded = false;
А зачем оно volatile?

2021-10-14 13:51 UTC, yurii-litvinov commented on HomeTask2/LazyFactory/Program.cs
> +        }
Это не надо, можно просто в библиотеку собирать, это настраивается в свойствах проекта. Main нужен только для .exe-шников.

2021-10-17 11:07 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/LazyTests.cs
> +            Assert.Throws<ArgumentNullException>(() => LazyFactory.CreateOneThreadLazy<object>(null));
Оно одно и то же проверяет?

2021-10-17 11:08 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/LazyTests.cs
> +            new Func<int>[] {()=> 32 },
```suggestion
            new Func<int>[] { () => 32 },
```

2021-10-17 11:10 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/LazyTests.cs
> +        };
Тесты должны разбивать пространство возможных входных данных на компоненты так, чтобы каждый компонент представлял собой множество входных данных, ведущих себя более-менее одинаково с точки зрения возможных ошибок, и покрывался одним тестом. Тут, мне кажется, три абсолютно одинаковых кейса.

2021-10-17 11:10 UTC, yurii-litvinov commented on HomeTask2/LazyFactory.Tests/LazyTests.cs
> +        }
Копипаст. Я в прошлой попытке сдачи объяснял, чего хочу

2021-11-22 18:35 UTC, Levliv commented
Тут должна быть фраза: "Если вы это сольете, то испортите решение матриц"

2021-12-09 21:47 UTC, closed without merging