Hometask4 - MyFTP
Levliv/HomeWorks pull request #6
Opened 2021-10-24 15:23 UTC by Levliv

2021-11-07 10:03 UTC, yurii-litvinov requested changes

2021-11-07 10:03 UTC, yurii-litvinov commented on HomeTask4/MyFTP/Server.cs
> +                var dataBytes = File.ReadAllBytes(path);
Вообще, когда работаете с файлами, старайтесь по максимуму не читать их в память --- файлы могут быть большими. У стримов есть метод [CopyToAsync](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copytoasync?view=net-5.0), который делает это аккуратно, вычитывая куски файла в небольшой буфер и скидывая в целевой стрим.

2021-11-07 10:03 UTC, yurii-litvinov commented on HomeTask4/MyFTP/Server.cs
> +                await Task.Run(async () =>
Не-а, тут пока делается await, другие клиенты не могут подключиться. То есть сервер асинхронный, но не многопоточный, что нарушает условие.

2021-11-07 10:03 UTC, yurii-litvinov commented on HomeTask4/MyFTP/Server.cs
> +                    var streamReader = new StreamReader(stream);
Они все IDisposable, так что должны быть using var

2021-11-07 10:03 UTC, yurii-litvinov commented on HomeTask4/MyFTP/Server.cs
> +                                streamBinaryWriter.Write(Encoding.UTF8.GetBytes("\n"));
По условию разделитель пробел вроде.

2021-11-07 10:03 UTC, yurii-litvinov commented on HomeTask4/MyFTP/Client.cs
> +        public void ClientMethod()
Он тоже должен быть асинхронный.

2021-11-22 18:41 UTC, Levliv commented on .github/workflows/main.yml
> +    branches: [ master, develop, hometask4 ]
Изначально идея была создавать новый Action для каждой отдельной домашки, и, когда все сливается в master, то запускается уже последний раз, чтобы еще разок проверить, ну и заодно проверять, не испортили ли мы случайно новым merge что-то из старых решений, но я в какой-то момент запутался и нейминг сломался.

2021-12-09 21:50 UTC, closed without merging